### ISSUE TITLE
Comments are broken for all window sizes below ~1300px in width

### ISSUE THREAD

**Issue by austinpray** [adispen/tpp#19]
![screenshot 2014-02-27 01 58 04](https://f.cloud.github.com/assets/2192970/2280227/eb02a37e-9f84-11e3-80da-0fc1fafbb60b.png)

**Comment by adispen** [comment]
this is an issue with your browser. it will automatically resize the boxes based on the window size.  try command minus a few times and reload the page.

**Comment by austinpray** [comment]
If the browser is below ~1300px in width the chat will fail to load. The initial values do not update when you resize the page.

**Comment by adispen** [comment]
you have to refresh after resize. open the console before you do, i left the height and width print statements in my js

**Comment by austinpray** [comment]
Why are you using JS to size the boxes?

**Comment by adispen** [comment]
sorry, its actually jQuery. and there is a responsive version of the site in the works

**Comment by adispen** [comment]
if you have a better fix feel free to send me a pull request
