### ISSUE TITLE
GH pages capacity problems

### ISSUE THREAD

**Issue by austinpray** [adispen/tpp#20]
Last time someone tried to use GH pages to host a the live updates they were shutdown for excessive bandwidth use. Consider migrating to AWS S3

**Comment by adispen** [comment]
i promise you this website isn't getting tons of traffic (currently at 158 concurrent, peaked at ~500 concurrent) so I'm not worried. but yes I have a backup. note that I threw this website together in an hour during class this morning

**Comment by kaushal** [comment]
Also, after serving the page the site uses none of gh's bandwidth. So from their perspective it's a static page. —
