### ISSUE TITLE
If desired, reddit livestream update can be embedded

### ISSUE THREAD

**Issue by alienth** [adispen/tpp#30]
The livestream can be embeded in an iframe with the following URL:

https://www.redditmedia.com/live/sw7bubeycai6hey4ciytwamw3a/embed

If this is something you'd be interested in having, I'd be happy to send a pull req.

**Comment by adispen** [comment]
will definitely be looking into this. the site is going to have some more stuff added soon so I will handle the integration. but thank you very much!

**Comment by alienth** [comment]
FYI, the live stream for Gen2 is now at http://www.reddit.com/live/m5n42gvbpyi6hdisciytwamw3a

**Comment by adispen** [comment]
yup sorry, was asleep
